---
- hosts: webservers 
  become: True
  tasks:
    - name: Install packages
      yum:
        name: "httpd"
        state: "present"
    - name: Start Apache server
      service:
        name: httpd
        state: started
        enabled: True
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/

    - name: debuging module
      shell: ps aux
      register: output

    - name: show the value of output
      debug: var=output

    - name: Create required users
      hosts: all
      vars:
      usernames:
      - devs
      - security
      - admins
      - group:
        name: web
        state: present

     - user:
      name: "{{ item }}"
      state: present
      groups: web
      append: yes
      with_items: "{{ usernames }}"
...
